In [1]:
import numpy as np

In [2]:
main_mat = np.array([
    [1,12,3,32],
    [8,12,3,14],
    [0,6,1,11],
    [18,4,2,2]
])

In [3]:
my_filter = np.array([
    [1,-1,1],
    [1,-1,1],
    [1,-1,1]
])

In [4]:
# my_filter = np.array([
#     [1,-2,3],
#     [3,3,-1],
#     [4,-8,1]
# ])

In [5]:
my_filter.shape

(3, 3)

In [6]:
def get_mat_idx(i,j,main_mat):
    if i<0 or j<0 or i>=main_mat.shape[0] or j>=main_mat.shape[1]:
        return 0
    return main_mat[i][j]

In [7]:
def apply_conv(main_mat,filter_mat):
    new_mat = np.zeros_like(main_mat)
    for i in range(new_mat.shape[0]):
        for j in range(new_mat.shape[1]):
            new_mat[i][j]=0.
            for i_f in range(filter_mat.shape[0]):
                for j_f in range(filter_mat.shape[1]):
                    new_mat[i][j]+=get_mat_idx(i+i_f-math.floor(filter_mat.shape[0]/2),j+j_f-math.floor(filter_mat.shape[1]/2),main_mat)*filter_mat[filter_mat.shape[0]-1-i_f][filter_mat.shape[1]-1-j_f]
    return new_mat

In [8]:
import math


In [9]:
apply_conv(apply_conv(main_mat,my_filter),my_filter)

array([[ -59,  203, -257,  234],
       [ -45,  232, -311,  298],
       [  -2,  145, -217,  224],
       [  33,   30,  -73,   94]])

In [10]:
apply_conv(main_mat,apply_conv(my_filter,my_filter))

array([[ -63,  112, -323,  342],
       [ -66,  130, -349,  350],
       [  56,   20, -191,  169],
       [ 114,  -52,  -80,   68]])

In [11]:
apply_conv(my_filter,my_filter)

array([[-4,  6, -4],
       [-6,  9, -6],
       [-4,  6, -4]])

In [12]:
my_filter

array([[ 1, -1,  1],
       [ 1, -1,  1],
       [ 1, -1,  1]])

In [13]:
m = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])

In [14]:
f=np.array([
    [-1,-2,-1],
    [0,0,0],
    [1,2,1]
])

In [15]:
apply_conv(m,f)

array([[-13, -20, -17],
       [-18, -24, -18],
       [ 13,  20,  17]])

In [16]:
import scipy.signal

In [17]:
scipy.signal.convolve2d(m, f, mode='same')

array([[-13, -20, -17],
       [-18, -24, -18],
       [ 13,  20,  17]])

In [18]:
apply_conv(apply_conv(main_mat,my_filter),my_filter)

array([[ -59,  203, -257,  234],
       [ -45,  232, -311,  298],
       [  -2,  145, -217,  224],
       [  33,   30,  -73,   94]])

In [19]:
scipy.signal.convolve2d(scipy.signal.convolve2d(main_mat, my_filter, mode='same'),my_filter,mode='same')

array([[ -59,  203, -257,  234],
       [ -45,  232, -311,  298],
       [  -2,  145, -217,  224],
       [  33,   30,  -73,   94]])

In [20]:
apply_conv(main_mat,apply_conv(my_filter,my_filter))

array([[ -63,  112, -323,  342],
       [ -66,  130, -349,  350],
       [  56,   20, -191,  169],
       [ 114,  -52,  -80,   68]])

In [21]:
scipy.signal.convolve2d(main_mat,scipy.signal.convolve2d(my_filter, my_filter, mode='same'),mode='same')

array([[ -63,  112, -323,  342],
       [ -66,  130, -349,  350],
       [  56,   20, -191,  169],
       [ 114,  -52,  -80,   68]])